# Site settings
course_name: AIMS5740 Generative Artificial Intelligence
course_description: |
    <p>This course covers mathematical and computational foundations of generative modeling, as well as applications in engineering, design, science, and the arts. The topics include foundation models, deep learning models, variational autoencoders, generative adversarial networks, autoregressive models such as Transformers, neural text decoding, prompt programming, and detection of generated content. Applications to language models and multimodality systems, as well as social responsibility in generative AI.

course_semester: "Spring 2025"

baseurl: "/AIMS5740-website" # the subpath of your site, e.g. /blog/
url: "https://ltl3A87.github.io" # the base hostname & protocol for your site
repository: "ltl3A87/AIMS5740-website"

schoolname: "CUHK"
schoolurl: "https://www.cuhk.edu.hk"

address: |
    Department of Computer Science & Engineering
    The Chinese University of Hong Kong
    Hong Kong

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop', 'vendor']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: false
    lectures:
        output: true
    tutorials:
        output: false
    projects:
        output: false
    assignments:
        output: false
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
